### ISSUE TITLE
Documentation link points to the wrong URL

### ISSUE THREAD

**Issue by jonleverrier** [stenvdb/craft-download-assets#1]
![screen shot 2019-03-06 at 14 36 50](https://user-images.githubusercontent.com/2373940/53885236-80c2f380-401d-11e9-8ed5-ae69bbad9976.png)

In the Craft Plugin Store, the documentation link points to:
```
https://github.com/stenvdb/download-assets/blob/master/README.md
```
Which returns a 404. Should point to:
```
https://github.com/stenvdb/craft-download-assets/blob/master/README.md
```

**Comment by stenvdb** [comment]
Thanks for pointing that out, appears to have fixed itself though.. anyway it's pointing to the correct URL now.
