### ISSUE TITLE
Styling not correct on commerce order fields

### ISSUE THREAD

**Issue by ruudvdboom** [stenvdb/craft-download-assets#5]
The styling is not correct on assets field viewed on commerce orders. The order doesn't have an delete button in "view order" mode. Which messes up the styling.

When clicking on edit order the problem is gone.

<img width="379" alt="Screenshot 2020-05-15 at 16 48 03" src="https://user-images.githubusercontent.com/14345687/82063542-e869d980-96cb-11ea-992d-e87db4577ebd.png">

**Comment by stenvdb** [comment]
A very late response (sorry!) but I have fixed this issue. Also the fact that the download button didn't actually do anything on order pages.
